BASE=dimensionality-reduction
INCLUDEDIR=/Users/neil/lawrennd/lamd/lamd/makefiles
SCRIPTDIR=/Users/neil/lawrennd/lamd/lamd/scripts
include $(INCLUDEDIR)/make-talk-flags.mk
include $(INCLUDEDIR)/make-talk.mk
