name: Documentation and Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
      - name: Install dependencies
        run: |
          # Install all dependencies including docs group
          poetry install --with docs
      - name: Test documentation build
        run: |
          cd docs
          poetry run python test_build.py
      - name: Build documentation
        run: |
          cd docs
          poetry run sphinx-build -b html . _build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
        if: github.ref == 'refs/heads/main'
  
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=lamd --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false 