name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Install linting tools
      run: |
        poetry run pip install flake8 black isort mypy
        
    - name: Check formatting with black
      run: |
        poetry run black --check --diff .
        
    - name: Check import sorting with isort
      run: |
        poetry run isort --check-only --diff .
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --select=E,W,F,C,N --ignore=E203,W503
        
    - name: Install type stubs
      run: |
        poetry run pip install types-PyYAML
        
    - name: Type check with mypy
      run: |
        poetry run mypy --strict --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs lamd/ 